CREATE DATABASE Football
USE Football
CREATE TABLE Stadions
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(30) NOT NULL,
HourPrice DECIMAL(18,2) NOT NULL,
Capacity INT NOT NULL
)
CREATE TABLE Users 
(
Id INT PRIMARY KEY IDENTITY,
FullName NVARCHAR(50)NOT NULL,
Email NVARCHAR(50)NOT NULL
)
CREATE TABLE Reservations
(
Id INT PRIMARY KEY IDENTITY,
StartDate DATETIME2,
EndDate DATETIME2,
StadionId INT CONSTRAINT ST_CHECK FOREIGN KEY REFERENCES Stadions(Id),
UserId INT CONSTRAINT UI_CHECK FOREIGN KEY REFERENCES Users(Id) 
)
SELECT *FROM Stadions